# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'health_cards', git: 'https://github.com/dvci/health_cards.git'
