#! /usr/bin/env ruby

require 'nokogiri'

toc = Nokogiri::XML(IO.read("output/toc.html"))

output = []
toc.search("#segment-content > div > div > div > div > div > table a").each do |a|
  output << {
    id: a['href'].gsub('.html', ''),
    title: a.children[0].text,
    mdIcon: "description",
    url: a['href']
  }
end

output.map! do |o|
  # Google Fonts - Material "Description" icon is embedded below
  # https://fonts.google.com/icons?selected=Material+Icons&icon.query=document
  <<~HEREDOC.strip
    {
      id: "#{o[:id]}",
      title: "#{o[:title]}",
      icon: `<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#FFFFFF"><path d="M0 0h24v24H0z" fill="none"/><path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z"/></svg>`,
      handler: () => {
        document.location = "#{o[:url]}";
      }
    }
  HEREDOC
end

File.open("custom-template/includes/ninja-keys.html", "w") { |f| f.write(output.join(",\n"))}