#!/usr/bin/env bash

source script/validate-helper.sh

validate_example examples/Scenario1Bundle.json shc-vaccination-bundle-ad &&
validate_example examples/Scenario1Bundle.json shc-vaccination-bundle-dm &&
validate_example examples/Scenario2Bundle.json shc-vaccination-bundle-ad &&
validate_example examples/Scenario2Bundle.json shc-vaccination-bundle-dm &&
validate_example examples/Scenario3Bundle.json shc-covid19-laboratory-bundle-ad &&
validate_example examples/Scenario3Bundle.json shc-covid19-laboratory-bundle-dm