on:
  issues:
    types: labeled
  pull_request:
    types: labeled
jobs:
  notify:
    if: ${{contains(github.event.*.labels.*.name, 'early-adopter-review')}}
    runs-on: ubuntu-latest
    steps:
      - name: Notify zulip stream
        run: |
          pip3 install zulip
          zulip-send \
            --site ${{secrets.ZULIP_SITE}} \
            --api-key ${{secrets.ZULIP_API_KEY}} \
            --user ${{secrets.ZULIP_USER}} \
            --stream ${{secrets.ZULIP_STREAM}} \
            --subject "Early Adopters: Review Request" \
            --message "@*shc-ig-early-adopters*: [#${{github.event[github.event_name].number}}: ${{github.event[github.event_name].title}}](${{github.event[github.event_name].html_url}}) is ready for review"
  notify-test:
    if: ${{contains(github.event.*.labels.*.name, 'test-zulip-notification')}}
    runs-on: ubuntu-latest
    steps:
      - name: Notify zulip stream (TEST)
        env:
          ISSUE_TITLE:  ${{format('{0}{1}', github.event.issue.title, github.event.pull_request.title)}}
          ISSUE_URL: ${{format('{0}{1}', github.event.issue.html_url, github.event.pull_request.html_url)}}
          ISSUE_NUMBER: ${{format('{0}{1}', github.event.issue.number, github.event.pull_request.number)}}
        run: |
          pip3 install zulip
          zulip-send \
            --site ${{secrets.ZULIP_SITE}} \
            --api-key ${{secrets.ZULIP_API_KEY}} \
            --user ${{secrets.ZULIP_USER}} \
            --stream ${{secrets.ZULIP_TEST_STREAM}} \
            --subject "Early Adopters: Review Request" \
            --message "@*shc-ig-early-adopters*: [#${ISSUE_NUMBER}: ${ISSUE_TITLE}](${ISSUE_URL}) is ready for review"
